calendar = [
'August 1 LGBTQ Art Show Opening 527 2nd, Eureka 5 - 9 pm, show 2 - 31 mon fri 10 - 3',
'August 1 PROTEST, Hum Co courthouse 12 - 2 pm',
'August 3 Teen Creative Art Group 5:30 7pm. vail@rhizomewellness.org',
'August 4 "WTF is the World", 2 - 3pm, vail@rhizomewellness.org',
'August 4, 18 Gender Expansive uterine condition support group 7p, maxi2sdoula@gmail.com',
'August 6 SUD Recovery Group for adults, 5:30 - 7pm, vail@rhizomewellness.org',
"August 7, 14 Wiyot tours, 5 & 7 pm, Da Gou Rou Louwi' Cultural Center, 417 2nd Eureka",
'Aug. 7 "Priscilla" 6/7 pm Arcata theater lounge',
'Fierce Resist Dance, The Basement, Arcata',
'August 8 Arcata Lantern Floating Ceremony: Lantern making 9am - 1:30 pm Arc. Plaza, Program 7:30 pm Klopp lake',
"Back to Fool Bingo, 5/6 pm, Eureka Women's club",
"Can't be Tamed, 7:30/ 8 pm Exit Theatre Arc.",
"August 8 & 22 Rapid Response Network training, 11 - 2, Sanctuary Garden, Arc.",
'August 8 Dos Aguas, 10am - 12:30pm, Moonstone",
"August 9 Sapphic swim, noon. sapphicswim@gmail.com",
"August 10, 17, 24, 31 Queer Tarot journey,7 8 pm, zoom. Michaela@queerhumboldt.org",
'August 11, 18, 25 Adult Trans+ support group, 12 - 1 pm Aisha@queerhumboldt.org",
"August 12, 19, 26 Cultivating Resilience, 5:30 - 7 pm zoom. tinyurl.com/yc7tyjmb",
'August 15, Salmon Festival, 190 Klamath blvd, Klamath 10 - 6",
"Vintage Vibes Wildlife Refuge walk, 2 - 4 pm Aisha@queerhumboldt.og",
'Sapphic oil wrestling 6:30pm - 12 am 109 5th, Eureka. tinyurl.com/4jfs6f5t3',
'August 16 Humboldt Obon, 3 - 7 pm Creamery, Arcata',
'Sanctuary Sunday 12 - 4 Local Cidar Bar, Arc.',
'August 22 Madaket cruise, 9 - 11 am, Aisha@queerhumboldt.org',
    'Dyke Hike 11am suejh@humboldt1.com',
    'Speed dating/Friending tinyurl.com/yc2esaf6',
    "Goutsuwe'n (One Sky) Celebration, 4pm - 12am, Phelan Rd, Table Bluff"
'August 23 Lesbian Brunch 11 am, Haleydavisarted@gmail.com',
'August 26 Queer Climb, 6 - 9p, Far North Gym, Arcata',
'August 27 Scissor Sisters 6pm, McKinleyville,Vaiva: 831.295.4021',
'Out for Business, 5 - 7p Phatsy Klines Eureka',
'August 28 Big Mood Queer dance party, Richards Goat, 9pm 21+', 
];
