calendar = [
'Jan 1- Sapphic Swim, noon, 497-0049'
'Jan 2- 2SLGBTQIA+ Safespace Crescent City Methodist Church every Fri 6pm'
'Jan 3 - Trans Support Group Cresc. Cty Meth. Chr. 1st & 3rd Sat 5pm'
     'Sisters of Perpetual Indulgence, Jefferson Center Eka, 12pm'
'Jan 4 - LGBTQIA+ AA 1944 Central McKinleyville Every Sun, noon'
     '- Sourdough Focaccia, 11am-1pm, aisha@queerhumboldt.org'
'Jan 5 - EYE Youth Club 837 H Arc., Mondays 3pm'
     '- Queer Tarot Journey, Mondays 7-8:30 Zoom michaela@queerhumboldt.org'
'Jan 6 - Adult Trans Support Group, 12-1, Tuesdays'
'Jan 7 - Queer & Peer Support (16-24) 523 T St Eureka, every Wed 5-5:50pm'
'Jan 7/15 - QWEERS CPH faculty/staff gathering, qweerss.humboldt.edu'
'Jan 8 - Queer Stitch & Sip, The Center Mck., 5:30-6:30pm'
'Jan 8, 22, 29 - Anna & The Situation, Speakeasy, 7-10pm, 21+'
'Jan 11 - dyke hike, 11am, suejh@humboldt1.com'
'Jan 14/28 - Healing from Relationship Harm 5:30-6:30pm, Aisha@queerhumboldt.org'
'Jan 15- Trans* Adult Potluck 5:30-7:30 julie@queerhumboldt.org'
'Jan 17 - Protest, courthouse, 12-2pm'
            '- 10 Years Fierce, 7pm, Playhouse'
'Jan 18 - Cheryl Rau Memorial, 3pm, HUUF'
'Jan 19- MLK Day, Adorni Center, time tba, eurekanaacp.org'
'Jan 23 - Queer Poetry Workshop 4-5:30pm alexis@queerhumboldt.org'
'Jan 25- L-Word layout deadline lword@sonic.net'
'Jan 26- Resistance & Remembrance, 5-6:30pm, CPH Native forum'
'Jan 28 - Surviving Digital Sexual Assault, 4-5pm, Lib 114, 826-5228'
             '- Queer Climb, Far North, 6pm'
'Jan 29 - Scissor Sisters 6pm Arwen 599-8562'
            '- Out for Business, Phatsy Kline's, 5-7pm'
'Jan 31- Know Your Rights, time tba, info@cdpueblo.com'
