calendar = [
'Oct 2 - Ghouls, Grrrls, Gays, and Theys. Basement, 8:30pm, 21+',
'Oct 5,12,19,26- Dream Group, Zoom, 7p Michaela@queerhumboldt.org',
'Oct 6,13,20,27 - Adult Trans+ Support group, 12-1p, aisha@queerhumboldt.org',
'Oct 7,14,21,28- Queer and Free, Zoom, 2:30 Michaela@queerhumboldt.org',
'Oct 8 - Trans Youth support group 4-5 pm Arc. MacKay@queerhumboldt.org',
'Oct 8, 10 - Savage Henry Comedy Festival, Summitt, 5 & 7pm',
'Oct 9 - 25 We Make It Burn, Eka/Arc parks, wemakeitburn.com',
'Oct 10 - Poetry Workshop + Open Mic, 11am-2pm',
     '--secondnaturedoc.com/virtual-screening, noon',
     "--Witchin' for the Kitchen, 5/6pm, Eka Women's Club, Eurekasisters.org",
     '--Tricks & Treats, Arc Thtr Lng, 7/8pm, 18+', 
'Oct 11 - Chinatown Memorial Celebration, 1-4pm, 1st and E, Eureka',
     '--Indigenous Foods Festival, Wiyot Plaza CPH, 11am-5pm',
'Oct 13,20,27 - Neurodivergent Online Support Group, 5-6p, Michaela@queerhumboldt.org',
'Oct 17 - No Kings/Vote Early, 12-2, Eka Crthse',
   '--2S Conference, 10-4, HCOE',
   '--HRD, 5/6, Franchesci Hall Rdwd Acres',
   '--Girl Trouble, Plhs, 6pm',
   '--SoHum Pride, Olde Riverwood, 9pm-2am, 21+',
'Oct 19-23 - CCDOR, CPH, hsu.link/cdor',
    '--Oct 22, Judge Abby, Goodwin Forum, 3pm',
'Oct 23 - Big Mood Queer dance party, Richards Goat, 9pm 21+',
'Oct 24 - dyke hike, 11am, suejh@humboldt1.com',
   '--Stop Amazon Walk, 11-1, Airport Business Park',
'Oct 24, 25- The Good Body, Plhs, 7p Sat/2p Sun, 13+',
'Oct 25 - lesbian brunch, Vaiva 831-295-4021',
'Oct 28 - Queer Climb, 6-9p, Far North Gym, Arcata',
'Oct 29 -Out for Business, 5-7p Phatsy Klines Eureka',
   '--Scissor Sisters, 6pm, Vaiva 831-295-4021',
   '--90s Halloween Film Night, 6pm, Summitt',
'Oct 30 - Queer karaoke, 8-11:30pm, Summitt',
'Nov 1 - Dia de los Muertos, Eka Thtr, 4-7pm', 
];
